### ISSUE TITLE
scikit-learn missing from `requirements.txt`

### ISSUE THREAD

**Issue by eguiraud** [iris-hep/analysis-grand-challenge#140]
It's now a mandatory dependency:

```
Traceback (most recent call last):
  File "/home/blue/Scratchpad/work/agc/analysis-grand-challenge/analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.py", line 615, in <module>
    model_even = XGBClassifier()
                 ^^^^^^^^^^^^^^^
  File "/home/blue/Tools/miniconda3/envs/agc-py311/lib/python3.11/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/blue/Tools/miniconda3/envs/agc-py311/lib/python3.11/site-packages/xgboost/sklearn.py", line 1422, in __init__
    super().__init__(objective=objective, **kwargs)
  File "/home/blue/Tools/miniconda3/envs/agc-py311/lib/python3.11/site-packages/xgboost/sklearn.py", line 584, in __init__
    raise ImportError(
ImportError: sklearn needs to be installed in order to use this module
```

**Comment by eguiraud** [comment]
(I would have opened a PR that adds it but the current requirements.txt specifies exact versions for all packages and I can't use those versions on my system because I'm on Python 3.11 -- see also #141 )
